export const AFFIRMATIONS: Record<string, string[]> = {
  suave: [
    "He cantado en la regadera pensando que soy artista profesional",
    "He bailado solo en mi cuarto esta semana",
    "He llorado viendo una película de Disney",
    "Me he quedado dormido en una reunión o clase importante",
    "He fingido entender un chiste que no entendí",
    "He usado ropa al revés todo el día sin darme cuenta",
    "He hablado solo en público sin darme cuenta",
    "He saludado a alguien pensando que era otra persona",
    "He comido comida del piso aplicando la regla de los 5 segundos",
    "Me he echado un gas en público y disimulé como si nada",
    "He fingido estar ocupado para evitar hablar con alguien",
    "Me he tropezado en público y actué como si nada pasó",
    "He googleado algo súper básico que me daba pena no saber",
    "He fingido que ya conocía una canción para no parecer raro",
    "He escrito un mensaje larguísimo y lo borré antes de enviarlo",
    "He fingido que me gustó un regalo que recibí",
    "He cantado una canción con la letra completamente equivocada",
    "He pretendido estar hablando por teléfono para evitar a alguien",
    "Me he reído de mi propio chiste antes de contarlo",
    "He buscado mi propio nombre en Google",
    "He visto una serie completa en un solo día sin moverme del sillón",
    "He inventado una excusa para no ir a una fiesta y me quedé en casa",
    "He hablado con mi mascota como si fuera una persona",
    "Me he puesto a llorar con un comercial de televisión",
    "He mandado un mensaje al grupo equivocado",
  ],
  picante: [
    "He stalkeado el Instagram de {nombre} antes de conocerlo bien",
    "He mentido sobre mi edad en una aplicación de citas",
    "He revisado el celular de mi pareja sin permiso",
    "He besado a alguien de este grupo",
    "He cancelado planes solo porque me dio flojera salir",
    "He fingido saber de un tema para impresionar a {nombre}",
    "He hablado mal de alguien y esa persona estaba justo al lado",
    "He mentido en mi currículum o CV",
    "He copiado en un examen importante",
    "He revisado las redes sociales de mi ex esta semana",
    "He mandado un mensaje borracho del que me arrepentí al día siguiente",
    "He dicho 'ya estoy llegando' cuando ni me había parado del sillón",
    "He coqueteado con alguien solo para obtener algo gratis",
    "He fingido que me gusta la comida que {nombre} preparó",
    "He borrado chats para que mi pareja no los viera",
    "He fingido estar enfermo para no ir a trabajar",
    "He inventado una historia completa para salir de un problema",
    "Me he metido a una fiesta sin invitación",
    "He dicho que tengo novio/novia solo para que me dejen en paz",
    "He robado algo pequeño de una tienda alguna vez",
    "He fingido saber un idioma que no hablo",
    "He bloqueado a alguien y luego lo desbloqueé para stalkear",
    "He mandado un screenshot de una conversación privada",
    "He mentido sobre dónde estaba para no quedar mal",
    "He fingido que no vi el mensaje de {nombre} para no responder",
  ],
  extrema: [
    "He tenido una fantasía romántica con alguien de este grupo",
    "Le he puesto los cuernos a alguien en el pasado",
    "He mentido sobre mi número de parejas",
    "He tenido un encuentro íntimo en un lugar público",
    "He fingido un orgasmo",
    "He mandado fotos subidas de tono a alguien que no debía",
    "Me he besado con el ex o la ex de un amigo",
    "He tenido pensamientos sobre alguien de este grupo que no debería contar",
    "He coqueteado con alguien estando en una relación",
    "He inventado una historia falsa sobre mi vida íntima",
    "He tenido un crush secreto con alguien que {nombre} conoce bien",
    "Me arrepiento de algo que hice con alguien de este grupo",
    "He hecho algo íntimo en casa de {nombre} sin que se enterara",
    "He revisado las fotos privadas del celular de alguien más",
    "He mentido sobre dónde dormí una noche para cubrir algo",
    "He tenido sueños subidos de tono con alguien de aquí",
    "He mandado un mensaje coqueto a alguien comprometido",
    "He hecho algo en una borrachera que hasta la fecha nadie sabe",
    "He tenido una aventura con alguien que todos aquí conocen",
    "Me he quedado con ganas de besar a alguien de este grupo hoy",
    "He dicho 'te amo' sin sentirlo de verdad",
    "He usado una app de citas estando en una relación",
    "He besado a alguien minutos después de conocerlo",
    "He hecho algo sexual en el trabajo o la escuela",
    "He sido infiel y nunca me cacharon",
  ],
};
